sudo: false

language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
    - $HOME/.m2

os:
  - linux

env:
  matrix:
    - PROFILES='-Pjacoco -Pjdkapicheck'
    - PROFILES='-Pretrolambda'
    - PROFILES='-Pretrolambda -Pjacoco'
    - PROFILES='-Pretrolambda -Pjdkapicheck -DskipTests=true'

matrix:
  allow_failures:
    - env: PROFILES='-Pretrolambda -Pjdkapicheck -DskipTests=true'

install:
    - mvn ${PROFILES} clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
    - mvn ${PROFILES} clean test -B