sudo: false

language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

os:
  - linux

env:
  matrix:
    - PROFILES='-Pjacoco'
    - PROFILES='-Pretrolambda'
    - PROFILES='-Pretrolambda -Pjacoco'
    - PROFILES='-Pretrolambda -Pjdkapicheck -DskipTests=true'

matrix:
  allow_failures:
    - env: PROFILES='-Pretrolambda -Pjacoco'
    - env: PROFILES='-Pretrolambda -Pjdkapicheck -DskipTests=true'

install:
    - mvn ${PROFILES} install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
    - mvn ${PROFILES} test -B