sudo: false

language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

os:
  - linux

env:
  matrix:
    - PHASE='-Pjacoco'
    - PHASE='-Pretrolambda'
    - PHASE='-Pretrolambda -Pjacoco'
